services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Remind\HeadlessNews\:
    resource: '../Classes/*'

  GeorgRinger\News\Controller\NewsController:
    alias: Remind\HeadlessNews\Controller\NewsController
    public: true

  GeorgRinger\News\Controller\CategoryController:
    alias: Remind\HeadlessNews\Controller\CategoryController
    public: true

  GeorgRinger\News\Controller\TagController:
    alias: Remind\HeadlessNews\Controller\TagController
    public: true

  Remind\HeadlessNews\EventListener\ModifySolrSearchDocumentEventListener:
    tags:
      - name: event.listener

  Remind\HeadlessNews\EventListener\ModifySolrSuggestionDocumentEventListener:
    tags:
      - name: event.listener

  Remind\HeadlessNews\Service\JsonService:
    shared: false
